apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
  namespace: rapidconnect
data:
  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_CHANNEL: "channel1"

  # MySQL
  MYSQL_HOST: "db"
  MYSQL_DATABASE: "mydb"
  MYSQL_TABLE: "mytable"
