apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-server
  namespace: rapidconnect
  labels:
    app: worker-server
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: worker-server

  template:
    metadata:
      labels:
        app: worker-server
    spec:
      containers:
        - name: worker-server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: worker-server-config
            - secretRef:
                name: api-server-secrets   # reuse same credentials

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      imagePullSecrets:
        - name: regcred
