apiVersion: v1
kind: Secret
metadata:
  name: api-server-secrets
  namespace: rapidconnect
type: Opaque
stringData:
  # Redis
  REDIS_PASSWORD: "mypassword"

  # MySQL
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "password"
