scrape_configs:
  - job_name: "k3s-node"
    static_configs:
      - targets:
          - "<K3S_EC2_PRIVATE_IP>:9100"

  - job_name: "kube-state-metrics"
    static_configs:
      - targets:
          - "<K3S_EC2_PRIVATE_IP>:8080"

  - job_name: "api-server"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "<K3S_EC2_PRIVATE_IP>:5001"
