apiVersion: v1
kind: Service
metadata:
  name: client-app
  namespace: rapidconnect
spec:
  type: ClusterIP
  selector:
    app: client-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
